### ISSUE TITLE
test failures on Windows 7 OS

### ISSUE THREAD

**Issue by breisfeld** [xray/xray#360]
OS: Windows 7, 64 bit

```
$ python
Python 2.7.8 |Anaconda 2.1.0 (32-bit)| (default, Jul  2 2014, 15:13:35) [MSC v.1500 32 bit (Intel)] on win32
>>> import xray
>>> xray.__version__
'0.4.0'
```

Running the tests provided with xray generates the output below.

I understand the test errors probably result from the way in which Windows manages files, but the failures may be more significant.

```
$ nosetests xray

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..C:\Python27\Anaconda\lib\site-packages\scipy\io\netcdf.py:287: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  ), category=RuntimeWarning)
.........C:\Python27\Anaconda\lib\site-packages\xray\core\utils.py:53: FutureWarning: numpy equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  return ((arr1 == arr2) | (pd.isnull(arr1) & pd.isnull(arr2))).all()
.....EE.EE.E.EEE.E.EE.SSSSSSSSSSSSSSSS...S.SS.SSSSS.....SSS.............F...................S...................F....S......................F........................................S.............F............................F....................................................F.................................
======================================================================
ERROR: test_load_data (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 92, in test_load_data
    pass
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 87, in assert_loads
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpnniync.nc'

======================================================================
ERROR: test_orthogonal_indexing (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 211, in test_orthogonal_indexing
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpanlrts.nc'

======================================================================
ERROR: test_roundtrip_None_variable (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 108, in test_roundtrip_None_variable
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpinhb9v.nc'

======================================================================
ERROR: test_roundtrip_coordinates (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 182, in test_roundtrip_coordinates
    self.assertDatasetIdentical(original, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpezxsf_.nc'

======================================================================
ERROR: test_roundtrip_example_1_netcdf (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 165, in test_roundtrip_example_1_netcdf
    self.assertDatasetEqual(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpo5zwxy.nc'

======================================================================
ERROR: test_roundtrip_mask_and_scale (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 253, in test_roundtrip_mask_and_scale
    self.assertDatasetAllClose(encoded, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmp5jczpa.nc'

======================================================================
ERROR: test_roundtrip_object_dtype (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 137, in test_roundtrip_object_dtype
    self.assertDatasetIdentical(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpji2z1n.nc'

======================================================================
ERROR: test_roundtrip_string_data (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 144, in test_roundtrip_string_data
    self.assertDatasetIdentical(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmp7sj2iu.nc'

======================================================================
ERROR: test_roundtrip_test_data (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 73, in test_roundtrip_test_data
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpibvyaw.nc'

======================================================================
ERROR: test_write_store (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 68, in test_write_store
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 588, in create_store
    yield backends.ScipyDataStore(tmp_file, mode='w')
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpyy61n0.nc'

======================================================================
ERROR: test_zero_dimensional_variable (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 59, in test_zero_dimensional_variable
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 600, in roundtrip
    yield ds
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpfqemcm.nc'

======================================================================
FAIL: test_coords (xray.test.test_dataarray.TestDataArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataarray.py", line 408, in test_coords
    self.assertEquals(expected, actual)
AssertionError: 'Coordinates:\n  * x        (x) int64 -1 -2\n  * y        (y) int64 0 1 2' != 'Coordinates:\n  * x        (x) int32 -1 -2\n  * y        (y) int32 0 1 2'

======================================================================
FAIL: test_repr (xray.test.test_dataarray.TestDataArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataarray.py", line 34, in test_repr
    self.assertEqual(expected, repr(data_array))
AssertionError: "<xray.DataArray 'my_variable' (time: 2, x: 3)>\narray([[1, 2, 3],\n       [4, 5, 6]])\nCoordinates:\n    other    int64 0\n  * time     (time) int64 0 1\n  * x        (x) int64 0 1 2\nAttributes:\n    foo: bar" != "<xray.DataArray 'my_variable' (time: 2, x: 3)>\narray([[1, 2, 3],\n       [4, 5, 6]])\nCoordinates:\n    other    int32 0\n  * time     (time) int64 0 1\n  * x        (x) int64 0 1 2\nAttributes:\n    foo: bar"

======================================================================
FAIL: test_coords_properties (xray.test.test_dataset.TestDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataset.py", line 335, in test_coords_properties
    self.assertEqual(expected, actual)
AssertionError: 'Coordinates:\n  * x        (x) int64 -1 -2\n  * y        (y) int64 0 1 2\n    a        (x) int64 4 5\n    b        int64 -10' != 'Coordinates:\n  * x        (x) int32 -1 -2\n  * y        (y) int32 0 1 2\n    a        (x) int32 4 5\n    b        int32 -10'

======================================================================
FAIL: test_to_and_from_dataframe (xray.test.test_dataset.TestDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataset.py", line 1369, in test_to_and_from_dataframe
    assert expected.equals(actual), (expected, actual)
AssertionError: (   a    x
y        
0  1  bar,    a    x
y        
0  1  bar)

======================================================================
FAIL: test_converted_types (xray.test.test_variable.TestAsCompatibleData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_variable.py", line 813, in test_converted_types
    self.assertEqual(np.dtype(int), actual.dtype)
AssertionError: dtype('int32') != dtype('int64')

======================================================================
FAIL: test_count (xray.test.test_variable.TestVariable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_variable.py", line 758, in test_count
    self.assertEqual(actual.dtype, 'int64')
AssertionError: dtype('int32') != 'int64'

----------------------------------------------------------------------
Ran 368 tests in 5.705s

FAILED (SKIP=76, errors=11, failures=6)

```

**Comment by shoyer** [comment]
Thanks for the report! As you can probably tell, we have not tried xray on windows before.

I notice at least two issues:

- `os.remove` failures -- might be related to https://github.com/xray/xray/issues/341
- `int32` vs `int64` discrepancies -- this we can definitely fix (it's because numpy on windows uses `int` as an alias for `int32`, unlike every other platform)

Can you try installing netCDF4-python (`conda install netcdf4`) and let me know if you get new or different errors?

**Comment by breisfeld** [comment]
Thank you for the prompt response. 

Here is the test output after installing netcdf4 via conda:

```
...........C:\Python27\Anaconda\lib\site-packages\xray\core\utils.py:53: FutureWarning: numpy equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  return ((arr1 == arr2) | (pd.isnull(arr1) & pd.isnull(arr2))).all()
...E.....E..EE.................EE.S................SS.SSSS.SSSSSSES.....S.............................................F...................S...................F....S......................F........................................S.............F............................F....................................................F.................................
======================================================================
ERROR: test_write_store (xray.test.test_backends.NetCDF3ViaNetCDF4DataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 68, in test_write_store
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 609, in create_store
    format='NETCDF3_CLASSIC')
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpcrovke.nc'

======================================================================
ERROR: test_dump_and_open_encodings (xray.test.test_backends.NetCDF4DataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 539, in test_dump_and_open_encodings
    self.assertArrayEqual(ds.variables['time'], np.arange(10) + 4)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpb6uvr4.nc'

======================================================================
ERROR: test_open_encodings (xray.test.test_backends.NetCDF4DataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 518, in test_open_encodings
    self.assertDictEqual(actual_encoding, expected['time'].encoding)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpw6k3xg.nc'

======================================================================
ERROR: test_open_group (xray.test.test_backends.NetCDF4DataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 336, in test_open_group
    open_dataset(tmp_file, group='bar')
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpokud5r.nc'

======================================================================
ERROR: test_write_groups (xray.test.test_backends.NetCDF4DataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 368, in test_write_groups
    self.assertDatasetIdentical(data2, actual2)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpmk9aat.nc'

======================================================================
ERROR: test_write_store (xray.test.test_backends.NetCDF4DataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 68, in test_write_store
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 281, in create_store
    yield backends.NetCDF4DataStore(tmp_file, mode='w')
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpioapvh.nc'

======================================================================
ERROR: test_write_store (xray.test.test_backends.ScipyOnDiskDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 68, in test_write_store
    self.assertDatasetAllClose(expected, actual)
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 588, in create_store
    yield backends.ScipyDataStore(tmp_file, mode='w')
  File "C:\Python27\Anaconda\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_backends.py", line 273, in create_tmp_file
    os.remove(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\breisfel\\appdata\\local\\temp\\tmpspbwg3.nc'

======================================================================
FAIL: test_coords (xray.test.test_dataarray.TestDataArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataarray.py", line 408, in test_coords
    self.assertEquals(expected, actual)
AssertionError: 'Coordinates:\n  * x        (x) int64 -1 -2\n  * y        (y) int64 0 1 2' != 'Coordinates:\n  * x        (x) int32 -1 -2\n  * y        (y) int32 0 1 2'

======================================================================
FAIL: test_repr (xray.test.test_dataarray.TestDataArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataarray.py", line 34, in test_repr
    self.assertEqual(expected, repr(data_array))
AssertionError: "<xray.DataArray 'my_variable' (time: 2, x: 3)>\narray([[1, 2, 3],\n       [4, 5, 6]])\nCoordinates:\n    other    int64 0\n  * time     (time) int64 0 1\n  * x        (x) int64 0 1 2\nAttributes:\n    foo: bar" != "<xray.DataArray 'my_variable' (time: 2, x: 3)>\narray([[1, 2, 3],\n       [4, 5, 6]])\nCoordinates:\n    other    int32 0\n  * time     (time) int64 0 1\n  * x        (x) int64 0 1 2\nAttributes:\n    foo: bar"

======================================================================
FAIL: test_coords_properties (xray.test.test_dataset.TestDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataset.py", line 335, in test_coords_properties
    self.assertEqual(expected, actual)
AssertionError: 'Coordinates:\n  * x        (x) int64 -1 -2\n  * y        (y) int64 0 1 2\n    a        (x) int64 4 5\n    b        int64 -10' != 'Coordinates:\n  * x        (x) int32 -1 -2\n  * y        (y) int32 0 1 2\n    a        (x) int32 4 5\n    b        int32 -10'

======================================================================
FAIL: test_to_and_from_dataframe (xray.test.test_dataset.TestDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_dataset.py", line 1369, in test_to_and_from_dataframe
    assert expected.equals(actual), (expected, actual)
AssertionError: (   a    x
y        
0  1  bar,    a    x
y        
0  1  bar)

======================================================================
FAIL: test_converted_types (xray.test.test_variable.TestAsCompatibleData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_variable.py", line 813, in test_converted_types
    self.assertEqual(np.dtype(int), actual.dtype)
AssertionError: dtype('int32') != dtype('int64')

======================================================================
FAIL: test_count (xray.test.test_variable.TestVariable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Anaconda\lib\site-packages\xray\test\test_variable.py", line 758, in test_count
    self.assertEqual(actual.dtype, 'int64')
AssertionError: dtype('int32') != 'int64'

----------------------------------------------------------------------
Ran 368 tests in 7.074s

FAILED (SKIP=18, errors=7, failures=6)

```

**Comment by shoyer** [comment]
I think I should be able to fix most of these pretty straightforwardly. Most of the OS errors are because we aren't closing files that we really should close.

Here's one question that I'm not quite sure about, though -- if `open_dataset` fails for some reason after opening a file should it ensure that any files it opened are closed? I suppose the answer is probably yes. This will be a difficult to test, though (at least on Unix machines).

**Comment by shoyer** [comment]
OK, I think everything should be working on master now. For what it's worth, these were mostly testing issues -- I didn't turn up any Windows specific bugs, though there was https://github.com/xray/xray/issues/341 (related to using the scipy.io.netcdf backend).

@breisfeld any chance you'd be up for testing this out again? `pip install https://github.com/xray/xray/archive/master.zip` should do it.

I can also try to get appveyor setup to run continuous testing on Windows.

**Comment by breisfeld** [comment]
Thank you for working to resolve these issues.

It is looking much better.

```
Python 2.7.8 |Anaconda 2.1.0 (32-bit)| (default, Jul  2 2014, 15:13:35) [MSC v.1500 32 bit (Intel)] on win32
>>> import xray
>>> xray.__version__
'0.4.0.dev'

$ nosetests xray
.............D:\Python27\Anaconda\lib\site-packages\xray\core\utils.py:54: FutureWarning: numpy equal will not check obj
ect identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will
change.
  return ((arr1 == arr2) | (pd.isnull(arr1) & pd.isnull(arr2))).all()
.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.................................SSSSSSSSSSSSSSSS...S.SS.SSSSS.....SS
S..................................S............................S.......................................................
........S..............................................F....................................................F...........
......................
======================================================================
FAIL: test_converted_types (xray.test.test_variable.TestAsCompatibleData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Python27\Anaconda\lib\site-packages\xray\test\test_variable.py", line 813, in test_converted_types
    self.assertEqual(np.dtype(np.int64), actual.dtype)
AssertionError: dtype('int64') != dtype('int32')

======================================================================
FAIL: test_count (xray.test.test_variable.TestVariable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Python27\Anaconda\lib\site-packages\xray\test\test_variable.py", line 758, in test_count
    self.assertEqual(actual.dtype, 'int64')
AssertionError: dtype('int32') != 'int64'

----------------------------------------------------------------------
Ran 395 tests in 4.786s

FAILED (SKIP=76, failures=2)

```

**Comment by shoyer** [comment]
I added integration testing with Appveyor on Windows and was able to fix the last few failing tests. So everything should be working now on master and will be checked automatically with every future change.
