### ISSUE TITLE
Can not import xray due to an ImportError: cannot import name OutOfBoundsDatetime

### ISSUE THREAD

**Issue by Xunius** [xray/xray#622]
Hi all,

I am testing out xray which was installed via conda. In the same environment I only installed python, numpy and xray. The installation went on smoothly, but when firing up a python session and importing xray, I got this error:

```
>>> import xray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eressci11/srf10mwu/miniconda/envs/testxray/lib/python2.7/site-packages/xray/__init__.py", line 4, in <module>
    from .core.dataset import Dataset
  File "/home/eressci11/srf10mwu/miniconda/envs/testxray/lib/python2.7/site-packages/xray/core/dataset.py", line 16, in <module>
    from .. import conventions
  File "/home/eressci11/srf10mwu/miniconda/envs/testxray/lib/python2.7/site-packages/xray/conventions.py", line 9, in <module>
    from pandas.tslib import OutOfBoundsDatetime
ImportError: cannot import name OutOfBoundsDatetime
```
I also tried reinstall it by `conda install -f xray` but didn't help.

Some version info:

conda:             3.16.0
pandas:           0.17.0
xray:                0.6.0
python:             2.7.10
numpy:             1.10.0

Please help

**Comment by jhamman** [comment]
We are still working out a few issues (#617 #618) with xray, pandas, and numpy for numpy version 1.10.  Can you try using numpy 1.9 and let us know how that goes?

**Comment by shoyer** [comment]
Are you sure that you have pandas installed correctly? It looks like something is broken with your pandas install -- `from pandas.tslib import OutOfBoundsDatetime` should work fine if you have pandas installed properly.

**Comment by Xunius** [comment]
@jhamman I tried downgrading numpy to 1.9.3 (by `conda install numpy=1.9`, if that is the right way of doing this), and didn't help. Still got the OutOfBoundsDatetime issue.
I repeated the same procedures on a different machine and all went on well. So might be something to do with this specific desktop.

**Comment by Xunius** [comment]
@shoyer I am not sure and I don't think I should be concerned. Xray is built on pandas so it should take care of that. Then conda should get pandas for me before installing xray. Finally `conda install pandas xray` didn't help.

**Comment by shoyer** [comment]
I'm suggesting that your pandas installation is the part that is broken. Can you try typing `from pandas.tslib import OutOfBoundsDatetime` from a terminal? If that doesn't work, then your conda build of pandas is broken, for whatever reason. My guess is that Continuum made a broken build of pandas by accident. If so, the work around would be to downgrade the pandas version.  You can also report it here: https://github.com/continuumio/anaconda-issues

**Comment by Xunius** [comment]
Update: I found a hidden folder in my HOME: `.local` in which there are some python modules: `.local/lib/python/site-packages/`. And `pandas` was found there. Can't remember when I installed it there but it seems that they are messing things around. After deleting the python folder from `./local`, I got a new error when trying to import xray:

```
>>> import xray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eressci11/srf10mwu/anaconda/envs/cdat/lib/python2.7/site-packages/xray/__init__.py", line 1, in <module>
    from .core.alignment import align, broadcast_arrays
  File "/home/eressci11/srf10mwu/anaconda/envs/cdat/lib/python2.7/site-packages/xray/core/alignment.py", line 7, in <module>
    from . import ops, utils
  File "/home/eressci11/srf10mwu/anaconda/envs/cdat/lib/python2.7/site-packages/xray/core/ops.py", line 8, in <module>
    import pandas as pd
  File "/home/eressci11/srf10mwu/anaconda/envs/cdat/lib/python2.7/site-packages/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.tslib (pandas/tslib.c:102460)
ValueError: numpy.dtype has the wrong size, try recompiling
```
Again it failed at pandas. Any clue?

**Comment by Xunius** [comment]
Update again:
After upgrading numpy from 1.9 to 1.10, I can now import xray and pandas. 
Issue can close now.
Thanks for both of you.
